# Example configuration for pool mode
[mode]
type = "Pool"

[mode.config]
share_difficulty = 1.0
variable_difficulty = true
min_difficulty = 0.1
max_difficulty = 1000.0
difficulty_adjustment_interval = 120
payout_threshold = 0.001
fee_percentage = 1.0

[network]
bind_address = "0.0.0.0:3333"
max_connections = 1000
connection_timeout = 30
keepalive_interval = 60

[bitcoin]
rpc_url = "http://127.0.0.1:8332"
rpc_user = "bitcoin"
rpc_password = "password"
network = "Mainnet"
block_template_timeout = 30

[database]
url = "postgresql://user:password@localhost/sv2d"
max_connections = 20
connection_timeout = 30
enable_migrations = true

[monitoring]
enable_metrics = true
metrics_bind_address = "127.0.0.1:9090"
enable_health_checks = true
health_check_interval = 30

[monitoring.metrics]
enabled = true
collection_interval = 10
prometheus_port = 9090
system_monitoring = true

[monitoring.metrics.labels]

[monitoring.health]
enabled = true
check_interval = 30
check_timeout = 10

[monitoring.health.alert_thresholds]
cpu_usage = 80.0
memory_usage = 85.0
connection_count = 900
rejection_rate = 10.0
response_time = 5000
database_connections = 8

[logging]
level = "info"
format = "Json"
output = "Stdout"
enable_correlation_ids = true

[security]
enable_authentication = true
api_key = "your-secure-api-key-here"
rate_limit_per_minute = 120
enable_tls = false