# SRI Pool config for regtest demo
authority_public_key = "9auqWEzQDVyd2oe1JVGFLMLHZtCo2FFqZwtKA5gd9xbuEu7PH72"
authority_secret_key = "mkDLTBBRxdBv998612qipDYoTK3YUrqLe8uWw7gu3iXbSrn2n"
cert_validity_sec = 3600
test_only_listen_adress_plain = "0.0.0.0:34250"
listen_address = "0.0.0.0:34254"

# Regtest mining address
coinbase_reward_script = "addr(bcrt1qe8le5cgtujqrx9r85e8q4r6zjy4c227zhgtyea)"

# Server Id
server_id = 1

# Pool signature for regtest demo
pool_signature = "SV2 Regtest Demo Pool"

# Template Provider config - sv2-tp listening on port 18447
tp_address = "127.0.0.1:18447"
shares_per_minute = 1.0
share_batch_size = 10